#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 18 17:51:25 CET 2023
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_stat_test_behav -key {Behavioral:sim_1:Functional:tb_stat_test} -tclbatch tb_stat_test.tcl -protoinst "protoinst_files/cryptoprocessor.protoinst" -view /home/jharing/git/2nd/chw2022g3/Assignment2/project_1/tb_stat_test_behav.wcfg -log simulate.log"
xsim tb_stat_test_behav -key {Behavioral:sim_1:Functional:tb_stat_test} -tclbatch tb_stat_test.tcl -protoinst "protoinst_files/cryptoprocessor.protoinst" -view /home/jharing/git/2nd/chw2022g3/Assignment2/project_1/tb_stat_test_behav.wcfg -log simulate.log

